import { Colors } from "@/@types/colorsState";

export const defaultColors: Colors = {
  // Tema modo light
  background: '',
  foreground: '',
  primary: '',
  primary_hover: '',
  primary_foreground: '',
  secondary: '',
  secondary_hover: '',
  secondary_foreground: '',
  accent: '',
  accent_hover: '',
  accent_foreground: '',
  muted: '',
  muted_hover: '',
  muted_foreground: '',

  danger: '',
  danger_hover: '',
  danger_foreground: '',
  warning: '',
  warning_hover: '',
  warning_foreground: '',
  success: '',
  success_hover: '',
  success_foreground: '',

  border: '',
  ring: '',
  chart1: '',
  chart2: '',
  chart3: '',
  chart4: '',
  chart5: '',

  // Tema modo dark
  dark_background: '',
  dark_foreground: '',

  dark_primary: '',
  dark_primary_hover: '',
  dark_primary_foreground: '',
  dark_secondary: '',
  dark_secondary_hover: '',
  dark_secondary_foreground: '',
  dark_accent: '',
  dark_accent_hover: '',
  dark_accent_foreground: '',
  dark_muted: '',
  dark_muted_hover: '',
  dark_muted_foreground: '',

  dark_danger: '',
  dark_danger_hover: '',
  dark_danger_foreground: '',
  dark_warning: '',
  dark_warning_hover: '',
  dark_warning_foreground: '',
  dark_success: '',
  dark_success_hover: '',
  dark_success_foreground: '',

  dark_border: '',
  dark_ring: '',

  dark_chart1: '',
  dark_chart2: '',
  dark_chart3: '',
  dark_chart4: '',
  dark_chart5: '',
};
