export type ColorsState = {
  background: string;
  foreground: string;
  card: string;
  cardForeground: string
  popover: string;
  popoverForeground: string
  primary: string;
  primaryForeground: string;
  secondary: string
  secondaryForeground: string
  muted: string
  mutedForeground: string
  accent: string
  accentForeground: string
  destructive: string
  destructiveForeground: string
  border: string
  input: string
  ring: string
  chart1: string
  chart2: string
  chart3: string
  chart4: string
  chart5: string
  darkBackground: string;
  darkForeground: string;
  darkCard: string;
  darkCardForeground: string
  darkPopover: string;
  darkPopoverForeground: string
  darkPrimary: string;
  darkPrimaryForeground: string;
  darkSecondary: string;
  darkSecondaryForeground: string;
  darkMuted: string;
  darkMutedForeground: string;
  darkAccent: string;
  darkAccentForeground: string;
  darkDestructive: string;
  darkDestructiveForeground: string;
  darkBorder: string;
  darkInput: string;
  darkRing: string;
  darkChart1: string;
  darkChart2: string;
  darkChart3: string;
  darkChart4: string;
  darkChart5: string;
};