name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Ativar Corepack e instalar pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.15.5 --activate

      - name: Instalar dependências
        run: pnpm install

      - name: Rodar os testes com Vitest
        run: pnpm test -- --coverage

      - name: Salvar cobertura de testes
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
